package com.yassir.bitbox.models.users;

import com.yassir.bitbox.enums.UserPrivilegesEnum;
import com.yassir.bitbox.models.Item.Item;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Set;


//---lombok---
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
//-------------
@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "userId", unique = true)
    private Long id;
    @Column(name = "userName", nullable = false)
    private String userName;
    @Column(name = "password", nullable = false)
    private String password;
    @Enumerated(EnumType.STRING)
    @Column(name = "privileges", nullable = false)
    private UserPrivilegesEnum privileges;


    //private Set<Item> items;

    //------------------------------------
    // NON GENERATED BY LOMBOK METHODS
    //------------------------------------
//    public void addItem(Item item){
//        this.items.add(item);
//    }
}
